Add single cell experiment converter
scverse/scverseio pull request #30
Opened 2023-04-27 15:43 UTC by mtmorgan

2023-04-27 15:58 UTC, mtmorgan commented on R/InMemoryAnnData.R
> +#'     var = data.frame(gene = 1:5, row.names = letters[1:5])
Maybe there's a confusion between `var_names` (names of columns in the `var` field) and `_index` metadata (the name of the var column that contains the index -- so like `var_index` or something...

2023-04-27 16:29 UTC, rcannood commented on R/InMemoryAnnData.R
> +#'     var = data.frame(gene = 1:5, row.names = letters[1:5])
According to https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.html#anndata.AnnData:

`var_keys()`: List keys of variable annotation [var](https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.var.html#anndata.AnnData.var).

`var_names`: Names of variables (alias for .var.index).

2023-04-28 06:02 UTC, mtmorgan commented on R/InMemoryAnnData.R
> +#'     var = data.frame(gene = 1:5, row.names = letters[1:5])
Ah I see. I used `var_names` in the print method when it should have been `var_keys()`. So we need a `var_keys`, method and also `.var.index`.

2023-04-28 06:04 UTC, rcannood commented on R/InMemoryAnnData.R
> +#'     var = data.frame(gene = 1:5, row.names = letters[1:5])
:+1: indeed. Though to some extend I guess the var keys is redundant, since we can just ask the colnames of the var. But we might as well add it to the abstract class.

Sorry for the short reply earlier, this was at the end of the previous session and I had to close my laptop ;)

2023-04-28 07:47 UTC, rcannood requested changes
Could you merge the main branch into this branch?

2023-04-28 08:28 UTC, merged