Add _keys functions
scverse/scverseio pull request #36
Opened 2023-04-28 11:52 UTC by mtmorgan

2023-04-28 13:44 UTC, rcannood requested changes

2023-04-28 13:44 UTC, rcannood commented on R/AbstractAnnData.R
> +    },
Can we not implement this in the abstract class?

```suggestion
    obs_keys = function() {
      names(self$obs)
    },
    #' @description Keys ('column names') of `var`.
    var_keys = function() {
      names(self$var)
    },
```

2023-04-28 13:44 UTC, rcannood commented on R/InMemoryAnnData.R
> +      names(private$.var)
If the other suggestion is accepted.

```suggestion
```

2023-04-28 13:51 UTC, mtmorgan commented on R/AbstractAnnData.R
> +    },
Is it guaranteed (or 'expected') that self$var returns something with `names()`?

2023-04-29 08:24 UTC, rcannood commented on R/AbstractAnnData.R
> +    },
Indeed :)

2023-04-29 08:55 UTC, rcannood approved these changes

2023-04-29 08:56 UTC, merged